import { NAME } from './constants';

const PREFIX = `${NAME}/`;

export const RECEIVE_COUNTRIES = `${PREFIX}RECEIVE_COUNTRIES`;

export const REQUEST_SERIES_LIST = `${PREFIX}REQUEST_SERIES_LIST`;
export const RECEIVE_SERIES_LIST = `${PREFIX}RECEIVE_SERIES_LIST`;

export const CREATE_SERIES = `${PREFIX}CREATE_SERIES`;
export const REQUEST_SERIES = `${PREFIX}REQUEST_SERIES`;
export const UPDATE_SERIES = `${PREFIX}UPDATE_SERIES`;
export const DELETE_SERIES = `${PREFIX}DELETE_SERIES`;
export const RECEIVE_SERIES = `${PREFIX}RECEIVE_SERIES`;

export const REQUEST_VIDEO_LIST = `${PREFIX}REQUEST_VIDEO_LIST`;
export const RECEIVE_VIDEO_LIST = `${PREFIX}RECEIVE_VIDEO_LIST`;

export const CREATE_VIDEO = `${PREFIX}CREATE_VIDEO`;
export const REQUEST_VIDEO = `${PREFIX}REQUEST_VIDEO`;
export const UPDATE_VIDEO = `${PREFIX}UPDATE_VIDEO`;
export const DELETE_VIDEO = `${PREFIX}DELETE_VIDEO`;
export const RECEIVE_VIDEO = `${PREFIX}RECEIVE_VIDEO`;

export const PREPARE_UPLOAD = `${PREFIX}PREPARE_UPLOAD`;
export const REDO_UPLOAD = `${PREFIX}REDO_UPLOAD`;
export const REMOVE_UPLOAD = `${PREFIX}REMOVE_UPLOAD`;
export const START_UPLOAD = `${PREFIX}START_UPLOAD`;
export const PROGRESS_UPLOAD = `${PREFIX}PROGRESS_UPLOAD`;
export const FINISH_UPLOAD = `${PREFIX}FINISH_UPLOAD`;

export const RECEIVE_STATUS_LIST = `${PREFIX}RECEIVE_STATUS_LIST`;
export const RECEIVE_STATUS = `${PREFIX}RECEIVE_STATUS`;

export const UPDATE_MESSAGE = `${PREFIX}UPDATE_MESSAGE`;

export const CREATE_RECOGNITION_SUCCESS = `${PREFIX}CREATE_RECOGNITION_SUCCESS`;
