SQLALCHEMY_DATABASE_URI = 'mysql+mysqldb://root:1qaz2wsx@10.126.0.7/PinStream?charset=utf8'
SQLALCHEMY_POOL_SIZE = 10
SQLALCHEMY_POOL_RECYCLE = 30
SQLALCHEMY_TRACK_MODIFICATIONS = False
SQLALCHEMY_ECHO = True